language: cpp

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
        - os: osx
          osx_image: xcode7.2

addons:
    apt:
        packages:
            - libpcap-dev
            - zlib1g-dev

install:
    - make
    - sudo make install
