language: cpp

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
        - os: osx
          osx_image: xcode7.2

before install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update       ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libpcap-dev zlib1g-dev; fi

script:
    - make
